DROP DATABASE IF EXISTS LOOKANDFUN;
CREATE DATABASE LOOKANDFUN;
USE LOOKANDFUN;

CREATE TABLE RECINTE(
PK_CODI_RECINTE INT auto_increment NOT NULL,
NOM_RECINTE VARCHAR(100) NOT NULL,
DIRECCIO varchar(200) NOT NULL,
CAPACITAT INT,

primary KEY (PK_CODI_RECINTE)
);

CREATE TABLE BUTACA(
PK_FK_CODI_RECINTE INT NOT NULL,
PK_FILA_BUTACA INT NOT NULL,
PK_NUMERO_BUTACA INT NOT NULL,

primary key (PK_FK_CODI_RECINTE, PK_FILA_BUTACA, PK_NUMERO_BUTACA)
);

CREATE TABLE ESDEVENIMENT(
PK_ID_ESDEVENIMENT INT auto_increment NOT NULL,
NOM varchar(100) NOT NULL,
DESCRIPCIO varchar(700),
DATA_INICI DATETIME NOT NULL,
DATA_FI DATETIME NOT NULL,
PREU DECIMAL(7, 2) DEFAULT 0,
AFORAMENT INT NOT NULL DEFAULT 0,

FK_CODI_RECINTE INT NOT NULL,

primary key (PK_ID_ESDEVENIMENT)
);

CREATE TABLE TIPUS(
PK_CODI_TIPUS INT auto_increment NOT NULL,
NOM_TIPUS varchar(100) NOT NULL,

primary key (PK_CODI_TIPUS)
);

CREATE TABLE PERSONA(
PK_CODI_PERSONA INT auto_increment NOT NULL,
DNI VARCHAR(20),/*DNI també pot significar NIF, passaport, etc.*/
NOM varchar(50) NOT NULL,
LLINATGES varchar(100) NOT NULL,
TELEFON varchar(20) NOT NULL,
EMAIL VARCHAR(100),
DATA_NAIXEMENT DATE NOT NULL,

primary key (PK_CODI_PERSONA)
);

CREATE TABLE ENTRADA(
PK_FK_ID_ENTRADA_ESDEVENIMENT INT NOT NULL,
PK_NUMERO_ENTRADA INT auto_increment NOT null,
DESCOMPTE DOUBLE DEFAULT 0,
DATA_ENTRADA datetime NOT null DEFAULT NOW(),

FK_CODI_PERSONA int default NULL,
FK_CODI_RECINTE INT NOT NULL,
FK_FILA_BUTACA INT default NULL,
FK_NUMERO_BUTACA INT default NULL,

primary KEY (PK_NUMERO_ENTRADA, PK_FK_ID_ENTRADA_ESDEVENIMENT)
);

CREATE TABLE TIPUS_ESDEVENIMENT(
PK_FK_CODI_TIPUS INT NOT NULL,
PK_FK_ID_TIPUS_ESDEVENIMENT INT NOT NULL,

PRIMARY KEY (PK_FK_CODI_TIPUS,PK_FK_ID_TIPUS_ESDEVENIMENT)
);

CREATE TABLE CATEGORIES(
ID_CAT int(11),
NOM_CAT varchar(30),
primary key (ID_CAT)
);




/*-------------------------------AFEGIM CONSTRAINTS---------------------------------*/
/*CONSTRAINTS A BUTACA*/
ALTER TABLE BUTACA ADD CONSTRAINT PK_FK_CODI_RECINTE FOREIGN KEY (PK_FK_CODI_RECINTE)
REFERENCES RECINTE (PK_CODI_RECINTE) ON UPDATE CASCADE ON DELETE CASCADE;

/*CONSTRAINTS A ESDEVENIMENT*/
ALTER TABLE ESDEVENIMENT ADD CONSTRAINT FK_CODI_RECINTE FOREIGN KEY (FK_CODI_RECINTE)
REFERENCES RECINTE(PK_CODI_RECINTE) ON UPDATE CASCADE ON DELETE RESTRICT;

/*CONSTRAINTS A ENTRADA*/
ALTER TABLE ENTRADA ADD CONSTRAINT PK_FK_ID_ENTRADA_ESDEVENIMENT FOREIGN KEY (PK_FK_ID_ENTRADA_ESDEVENIMENT)
REFERENCES ESDEVENIMENT (PK_ID_ESDEVENIMENT) ON UPDATE CASCADE ON DELETE RESTRICT;
--
ALTER TABLE ENTRADA ADD CONSTRAINT FK_CODI_PERSONA FOREIGN KEY (FK_CODI_PERSONA)
REFERENCES PERSONA (PK_CODI_PERSONA) ON UPDATE CASCADE ON DELETE RESTRICT;
--
ALTER TABLE ENTRADA ADD CONSTRAINT FK_BUTACA FOREIGN KEY (FK_CODI_RECINTE, FK_FILA_BUTACA, FK_NUMERO_BUTACA)
REFERENCES BUTACA (PK_FK_CODI_RECINTE, PK_FILA_BUTACA, PK_NUMERO_BUTACA) ON UPDATE CASCADE ON DELETE RESTRICT;

/*CONSTRAINTS A TIPUS_ESDEVENIMENT*/
ALTER TABLE TIPUS_ESDEVENIMENT ADD CONSTRAINT PK_FK_CODI_TIPUS FOREIGN KEY (PK_FK_CODI_TIPUS)
REFERENCES TIPUS (PK_CODI_TIPUS) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE TIPUS_ESDEVENIMENT ADD CONSTRAINT PK_FK_ID_TIPUS_ESDEVENIMENT FOREIGN KEY (PK_FK_ID_TIPUS_ESDEVENIMENT)
REFERENCES ESDEVENIMENT (PK_ID_ESDEVENIMENT) ON UPDATE CASCADE ON DELETE RESTRICT;