USE LOOKANDFUN;
/*INSERTAR DADES*/
/*ALTER TABLE ENTRADA MODIFY FK_CODI_RECINTE INT(11) DEFAULT NULL;*/ /*ALLOW NULL TO FK_CODI_RECINTE*/
INSERT INTO ESDEVENIMENT (NOM, DESCRIPCIO, DATA_INICI, DATA_FI, PREU, AFORAMENT, OCUPACIO, FK_CODI_RECINTE) VALUES ("DISCOTECA LOREM IPSUM", "LOREM LOREM IPSUM IPSUM", "2019-12-12", "2021-12-12", 0.00, 0, 0, 1);
INSERT INTO ENTRADA (PK_FK_ID_ENTRADA_ESDEVENIMENT, DESCOMPTE) VALUES (1, 0);