DROP DATABASE IF EXISTS LOOKANDFUN_ENTRADES_ESDEVENIMENTS;
CREATE DATABASE LOOKANDFUN_ENTRADES_ESDEVENIMENTS;
USE LOOKANDFUN_ENTRADES_ESDEVENIMENTS;

CREATE TABLE ESDEVENIMENT(
PK_ID_ESDEVENIMENT INT auto_increment NOT NULL,
NOM varchar(100) NOT NULL,
DESCRIPCIO varchar(700),
DATA_INICI DATETIME NOT NULL,
DATA_FI DATETIME NOT NULL,
PREU DECIMAL(7, 2) DEFAULT 0,
AFORAMENT INT NOT NULL DEFAULT 0,
OCUPACIO INT NOT NULL DEFAULT 0,
SOURCE_POSTER_EVENT varchar(128) DEFAULT NULL,

FK_CODI_RECINTE INT NOT NULL,

primary key (PK_ID_ESDEVENIMENT)
);

CREATE TABLE ENTRADA(
PK_ID INT auto_increment NOT null,
PK_FK_ID_ENTRADA_ESDEVENIMENT INT NOT NULL,
PK_NUMERO_ENTRADA INT NOT null,
DESCOMPTE DOUBLE DEFAULT 0,
DATA_ENTRADA datetime NOT null DEFAULT NOW(),

FK_CODI_PERSONA int default NULL,
FK_FILA_BUTACA INT,
FK_NUMERO_BUTACA INT,

primary KEY (PK_ID),
unique KEY (PK_NUMERO_ENTRADA, PK_FK_ID_ENTRADA_ESDEVENIMENT)
);

/*CONSTRAINTS A ENTRADA*/
ALTER TABLE ENTRADA ADD CONSTRAINT PK_FK_ID_ENTRADA_ESDEVENIMENT FOREIGN KEY (PK_FK_ID_ENTRADA_ESDEVENIMENT)
REFERENCES ESDEVENIMENT (PK_ID_ESDEVENIMENT) ON UPDATE CASCADE ON DELETE RESTRICT;





/*INSERTS*/
INSERT INTO ESDEVENIMENT (NOM, DESCRIPCIO, DATA_INICI, DATA_FI, SOURCE_POSTER_EVENT, FK_CODI_RECINTE) VALUES ('DISCOTECA LOREM IPSUM', 'LOREM IPSUM DOLOR SIT AMET', '2021-10-08 13:00', '2019-12-27', '1.jpg', 1);
INSERT INTO ESDEVENIMENT (NOM, DESCRIPCIO, DATA_INICI, DATA_FI, SOURCE_POSTER_EVENT, FK_CODI_RECINTE) VALUES ('XENV', 'LOREM IPSUM DOLOR SIT AMET', '2019-10-08', '2021-12-27', '1.jpg', 1);
INSERT INTO ESDEVENIMENT (NOM, DESCRIPCIO, DATA_INICI, DATA_FI, SOURCE_POSTER_EVENT, FK_CODI_RECINTE) VALUES ('EVENT SENSE ENTRADES', 'LOREM IPSUM DOLOR SIT AMET', '2021-10-08', '2019-12-27', '1.jpg', 1);
INSERT INTO ESDEVENIMENT (NOM, DESCRIPCIO, DATA_INICI, DATA_FI, PREU, AFORAMENT, SOURCE_POSTER_EVENT, FK_CODI_RECINTE) VALUES ('DISCOTECA LOREM IPSUM 3', 'LOREM IPSUM DOL...', '2020-01-18 13:00', '2020-01-08 12:00', 0, 3, 'default.png', 2);

INSERT INTO ENTRADA (PK_FK_ID_ENTRADA_ESDEVENIMENT, PK_NUMERO_ENTRADA) VALUES (1, 1);
INSERT INTO ENTRADA (PK_FK_ID_ENTRADA_ESDEVENIMENT, PK_NUMERO_ENTRADA) VALUES (1, 2);
INSERT INTO ENTRADA (PK_FK_ID_ENTRADA_ESDEVENIMENT, PK_NUMERO_ENTRADA) VALUES (1, 3);
INSERT INTO ENTRADA (PK_FK_ID_ENTRADA_ESDEVENIMENT, PK_NUMERO_ENTRADA) VALUES (1, 4);
INSERT INTO ENTRADA (PK_FK_ID_ENTRADA_ESDEVENIMENT, PK_NUMERO_ENTRADA) VALUES (2, 1);
INSERT INTO ENTRADA (PK_FK_ID_ENTRADA_ESDEVENIMENT, PK_NUMERO_ENTRADA) VALUES (2, 2);
INSERT INTO ENTRADA (PK_FK_ID_ENTRADA_ESDEVENIMENT, PK_NUMERO_ENTRADA) VALUES (2, 3);
INSERT INTO ENTRADA (PK_FK_ID_ENTRADA_ESDEVENIMENT, PK_NUMERO_ENTRADA) VALUES (2, 4);

SELECT MAX(PK_NUMERO_ENTRADA)+1 FROM ENTRADA WHERE PK_FK_ID_ENTRADA_ESDEVENIMENT = 1;